Assessment 06
RuthGichaba/tiny-theaters pull request #1
Opened 2022-04-11 14:10 UTC by RuthGichaba

2022-04-11 19:06 UTC, jmccann-dev-10 requested changes
Pretty good start so far, there are a few queries that need to be cleaned up because they are currently giving back incorrect data, but otherwise good job.  I really like how well organized the queries are.

2022-04-11 19:06 UTC, jmccann-dev-10 commented on rcttc-queries.sql
> +where email like '%.com'; -- 42 rows
I think this is giving back the customers WITH a .com

2022-04-11 19:06 UTC, jmccann-dev-10 commented on rcttc-queries.sql
> +group by r.customer_id, s.ticket_price;
The aggregates on these are giving back incorrect data.  The show total should be across all nights performed and not total per evening.

2022-04-11 19:06 UTC, jmccann-dev-10 commented on rcttc-schema.sql
> +);
These look really good, although some of the data is still repeated per table.

2022-04-13 19:21 UTC, RuthGichaba commented on rcttc-queries.sql
> +where email like '%.com'; -- 42 rows
Fixed it!

2022-04-13 19:22 UTC, RuthGichaba commented on rcttc-queries.sql
> +group by r.customer_id, s.ticket_price;
Should be correct now!

2022-04-13 19:23 UTC, RuthGichaba commented on rcttc-schema.sql
> +);
Adjusted the schema for shows so theater info is not repeated now~

2022-04-13 21:04 UTC, jmccann-dev-10 approved these changes
Excellent job, keep up the good work!

2022-04-13 21:10 UTC, merged